### ISSUE TITLE
Admin user cannot delete respondents

### ISSUE THREAD

**Issue by timdalton** [sqweelygig/moodle-mod-360#1]
Logged in as Moodle admin, viewing users at respondents.php. On clicking the 'delete' button the following error is reported:

Coding error detected, it must be fixed by a programmer: PHP catchable fatal error

Respondent doesn't get deleted.
![screen shot 2016-08-17 at 10 41 22](https://cloud.githubusercontent.com/assets/2805914/17731905/5b7e93c0-6467-11e6-9f89-31a7cd35855a.png)

**Comment by sqweelygig** [comment]
Tim,
The latest version (2016081701) should have resolved this error.
Cheers,
Andrew.
